"""Luau export: a small runtime library + a generated builder for this design.

The library is intentionally dependency free (no external modules) so it can be
pasted straight into a Roblox place: `ReplicatedStorage.UiForge`.
"""
from __future__ import annotations

from ..spec import DesignSpec, Node
from ..themes import hexs, color3

LIBRARY = r'''--!strict
-- UiForge.lua  —  generated by Roblox UI Forge
-- Tiny, dependency-free UI runtime.  Put it in ReplicatedStorage and require it.

local UiForge = {}

UiForge.Theme = __THEME__

local ASSETS = {}   -- filled by UiForge.bindAssets(map)
local SLICES = __SLICES__

local ALIGN = {
	left = Enum.TextXAlignment.Left,
	center = Enum.TextXAlignment.Center,
	right = Enum.TextXAlignment.Right,
}

function UiForge.bindAssets(map)
	for name, id in pairs(map) do
		if type(id) == "string" and id:find("rbxassetid://") then
			ASSETS[name] = id
		elseif type(id) == "number" and id > 0 then
			ASSETS[name] = "rbxassetid://" .. id
		end
	end
end

function UiForge.asset(name)
	return ASSETS[name]
end

function UiForge.new(className: string, props, parent: Instance?)
	local inst = Instance.new(className)
	for k, v in pairs(props or {}) do
		local ok, err = pcall(function()
			(inst :: any)[k] = v
		end)
		if not ok then
			warn("[UiForge] " .. className .. "." .. k .. " = " .. tostring(err))
		end
	end
	if parent then
		inst.Parent = parent
	end
	return inst
end

function UiForge.corner(inst: Instance, radius: number)
	return UiForge.new("UICorner", { CornerRadius = UDim.new(0, radius) }, inst)
end

function UiForge.stroke(inst: Instance, color: Color3, thickness: number?, transparency: number?)
	return UiForge.new("UIStroke", {
		Color = color,
		Thickness = thickness or 2,
		Transparency = transparency or 0,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	}, inst)
end

function UiForge.gradient(inst: Instance, from: Color3, to: Color3, rotation: number?)
	return UiForge.new("UIGradient", {
		Color = ColorSequence.new(from, to),
		Rotation = rotation or 90,
	}, inst)
end

-- Apply a 9-slice image if the asset exists, otherwise fall back to colour+corner.
function UiForge.skin(inst: Instance, assetName: string?, fallback: Color3?, radius: number?)
	if assetName then
		local id = ASSETS[assetName]
		if id then
			inst.Image = id
			inst.ScaleType = Enum.ScaleType.Slice
			local slice = SLICES[assetName]
			if slice then
				inst.SliceCenter = Rect.new(slice[1], slice[2], slice[3], slice[4])
				inst.SliceScale = 1
			end
			return inst
		end
	end
	if fallback then
		inst.BackgroundColor3 = fallback
		inst.BackgroundTransparency = 0
		if radius then
			UiForge.corner(inst, radius)
		end
	end
	return inst
end

function UiForge.text(parent: Instance, props)
	local p = props or {}
	return UiForge.new("TextLabel", {
		Name = p.name or "Text",
		Position = p.position or UDim2.fromScale(0, 0),
		Size = p.size or UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		Text = p.text or "",
		Font = p.font or Enum.Font.Gotham,
		TextSize = p.textSize or 24,
		TextColor3 = p.color or Color3.fromRGB(255, 255, 255),
		TextXAlignment = ALIGN[p.align or "left"] or Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Center,
		TextWrapped = p.wrapped ~= false,
		TextScaled = p.scaled or false,
		RichText = p.rich ~= false,
		ZIndex = p.zIndex or 1,
		TextTransparency = p.transparency or 0,
	}, parent)
end

function UiForge.panel(parent: Instance, opts)
	local o = opts or {}
	local inst = UiForge.new(o.class or "Frame", {
		Name = o.name or "Panel",
		Position = o.position or UDim2.fromScale(0, 0),
		Size = o.size or UDim2.fromScale(1, 1),
		BackgroundColor3 = o.color or Color3.fromRGB(20, 22, 30),
		BackgroundTransparency = o.transparency or 0,
		BorderSizePixel = 0,
		ZIndex = o.zIndex or 1,
		ClipsDescendants = o.clips or false,
		Visible = o.visible ~= false,
	}, parent)
	if o.class == "ImageLabel" or o.asset then
		inst.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		inst.BackgroundTransparency = 1
		UiForge.skin(inst :: any, o.asset, o.color, o.radius)
	elseif o.radius then
		UiForge.corner(inst, o.radius)
	end
	if o.stroke then
		UiForge.stroke(inst, o.stroke, o.strokeWidth or 2)
	end
	return inst
end

-- A real TextButton with hover / press feedback.
function UiForge.button(parent: Instance, opts)
	local o = opts or {}
	local btn = UiForge.new("TextButton", {
		Name = o.name or "Button",
		Position = o.position or UDim2.fromScale(0, 0),
		Size = o.size or UDim2.fromOffset(220, 72),
		BackgroundColor3 = o.color or Color3.fromRGB(0, 170, 255),
		BackgroundTransparency = o.transparency or 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = o.text or "",
		Font = o.font or Enum.Font.GothamBold,
		TextSize = o.textSize or 26,
		TextColor3 = o.textColor or Color3.fromRGB(255, 255, 255),
		ZIndex = o.zIndex or 2,
	}, parent)
	if o.asset then
		btn.BackgroundTransparency = 1
		btn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		UiForge.skin(btn, o.asset, o.color, o.radius)
	elseif o.radius then
		UiForge.corner(btn, o.radius)
	end
	if o.stroke then
		UiForge.stroke(btn, o.stroke, o.strokeWidth or 2)
	end
	if o.icon then
		local ic = UiForge.new("ImageLabel", {
			Name = "Icon",
			AnchorPoint = Vector2.new(0, 0.5),
			Position = UDim2.new(0, 16, 0.5, 0),
			Size = UDim2.fromOffset(o.iconSize or 30, o.iconSize or 30),
			BackgroundTransparency = 1,
			Image = ASSETS[o.icon] or "",
			ZIndex = btn.ZIndex + 1,
		}, btn)
		local pad = UiForge.new("UIPadding", { PaddingLeft = UDim.new(0, (o.iconSize or 30) + 26) }, btn)
		_ = ic; _ = pad
	end

	local idle = o.color or btn.BackgroundColor3
	local hover = o.hoverColor or idle:Lerp(Color3.new(1, 1, 1), 0.12)
	local down = o.pressedColor or idle:Lerp(Color3.new(0, 0, 0), 0.18)
	local stateAssets = o.states or {}

	local function setState(which: string)
		if not o.asset then
			btn.BackgroundColor3 = which == "hover" and hover or (which == "down" and down or idle)
		else
			local id = ASSETS[stateAssets[which] or o.asset]
			if id then
				btn.Image = id
			end
		end
	end

	btn.MouseEnter:Connect(function() setState("hover") end)
	btn.MouseLeave:Connect(function() setState("idle") end)
	btn.MouseButton1Down:Connect(function() setState("down") end)
	btn.MouseButton1Up:Connect(function() setState("hover") end)
	btn.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.Touch then
			setState("idle")
		end
	end)
	return btn
end

function UiForge.progress(parent: Instance, opts)
	local o = opts or {}
	local track = UiForge.new("Frame", {
		Name = o.name or "Progress",
		Position = o.position or UDim2.fromScale(0, 0),
		Size = o.size or UDim2.fromOffset(420, 22),
		BackgroundColor3 = o.trackColor or Color3.fromRGB(12, 14, 20),
		BorderSizePixel = 0,
		ClipsDescendants = true,
		ZIndex = o.zIndex or 1,
	}, parent)
	UiForge.corner(track, (o.size and o.size.Y.Offset or 22) / 2)
	local fill = UiForge.new("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(math.clamp(o.value or 0, 0, 1), 1),
		BackgroundColor3 = o.color or Color3.fromRGB(0, 190, 255),
		BorderSizePixel = 0,
		ZIndex = track.ZIndex + 1,
	}, track)
	UiForge.new("UICorner", { CornerRadius = UDim.new(1, 0) }, fill)
	function track:SetValue(v: number)
		fill.Size = UDim2.fromScale(math.clamp(v, 0, 1), 1)
	end
	return track
end

function UiForge.toggle(parent: Instance, opts)
	local o = opts or {}
	local on = o.value ~= false
	local theme = UiForge.Theme
	local track = UiForge.new("TextButton", {
		Name = o.name or "Toggle",
		Position = o.position or UDim2.fromScale(0, 0),
		Size = o.size or UDim2.fromOffset(76, 40),
		BackgroundColor3 = on and theme.accent or Color3.fromRGB(30, 33, 42),
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		ZIndex = o.zIndex or 2,
	}, parent)
	UiForge.new("UICorner", { CornerRadius = UDim.new(1, 0) }, track)
	local knob = UiForge.new("ImageLabel", {
		Name = "Knob",
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.new(on and 1 or 0, on and -8 or 8, 0.5, 0),
		Size = UDim2.fromOffset(30, 30),
		BackgroundColor3 = Color3.fromRGB(250, 250, 252),
		BorderSizePixel = 0,
		ZIndex = track.ZIndex + 1,
	}, track)
	UiForge.new("UICorner", { CornerRadius = UDim.new(1, 0) }, knob)
	local current = on
	local changed = Instance.new("BindableEvent")
	track.Activated:Connect(function()
		current = not current
		local goal = UDim2.new(current and 1 or 0, current and -8 or 8, 0.5, 0)
		knob.Position = goal
		track.BackgroundColor3 = current and theme.accent or Color3.fromRGB(30, 33, 42)
		changed:Fire(current)
	end)
	track.Changed = changed
	function track:SetValue(v: boolean)
		current = v
		knob.Position = UDim2.new(v and 1 or 0, v and -8 or 8, 0.5, 0)
		track.BackgroundColor3 = v and theme.accent or Color3.fromRGB(30, 33, 42)
	end
	return track
end

-- Animate any instance towards a property (tweens are optional, keep it simple).
function UiForge.pulse(inst: Instance, scale: number?, seconds: number?)
	local s = scale or 1.04
	local t = seconds or 0.12
	local tween = game:GetService("TweenService"):Create(inst, TweenInfo.new(t, Enum.EasingStyle.Quad), { Size = inst.Size * UDim2.fromScale(s, s) })
	tween:Play()
	task.delay(t * 2, function()
		local back = game:GetService("TweenService"):Create(inst, TweenInfo.new(t, Enum.EasingStyle.Quad), { Size = inst.Size * UDim2.fromScale(1 / s, 1 / s) })
		back:Play()
	end)
end

return UiForge
'''


def _hex(c) -> str:
    return hexs(c)


def theme_literal(pal) -> str:
    return (
        "{\n"
        f'\tstyle = "{pal.name}",\n'
        f'\tradius = {int(pal.radius)},\n'
        f'\tdark = {"true" if pal.dark else "false"},\n'
        f'\tbg = Color3.fromRGB{pal.bg_deep},\n'
        f'\tbgMid = Color3.fromRGB{pal.bg_mid},\n'
        f'\tpanel = Color3.fromRGB{pal.panel},\n'
        f'\tpanelHi = Color3.fromRGB{pal.panel_hi},\n'
        f'\tpanelLo = Color3.fromRGB{pal.panel_lo},\n'
        f'\tstroke = Color3.fromRGB{pal.stroke},\n'
        f'\taccent = Color3.fromRGB{pal.accent},\n'
        f'\taccentHi = Color3.fromRGB{pal.accent_hi},\n'
        f'\taccent2 = Color3.fromRGB{pal.accent2},\n'
        f'\ttext = Color3.fromRGB{pal.text},\n'
        f'\ttextDim = Color3.fromRGB{pal.text_dim},\n'
        f'\tsuccess = Color3.fromRGB{pal.success},\n'
        f'\twarn = Color3.fromRGB{pal.warn},\n'
        f'\tdanger = Color3.fromRGB{pal.danger},\n'
        "}"
    )


def lua_str(s: str) -> str:
    if s is None:
        return '""'
    out = (str(s).replace("\\", "\\\\").replace('"', '\\"')
           .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t"))
    return '"' + out + '"'


CLASS_FOR_KIND = {
    "panel": "Frame", "row": "Frame", "toast": "Frame", "slot": "Frame", "tab": "Frame",
    "button": "TextButton", "field": "Frame", "track": "Frame", "fill": "Frame",
    "badge": "Frame", "avatar": "ImageLabel", "icon": "ImageLabel", "divider": "Frame",
    "knob": "ImageLabel", "toggle": "Frame", "wheel": "ImageLabel", "minimap": "ImageLabel",
    "backdrop": "ImageLabel", "scrim": "Frame", "text": "TextLabel",
}

IMAGE_KINDS = {"avatar", "icon", "wheel", "minimap", "backdrop"}
SLICE_KINDS = {"panel", "row", "toast", "slot", "tab", "button", "field", "track", "fill", "badge"}


def node_entry(node: Node, spec: DesignSpec, asset_key: str | None, z: int) -> str | None:
    cw, ch = spec.canvas
    r = node.rect
    kind = node.kind
    p = node.props
    cls = CLASS_FOR_KIND.get(kind)
    if cls is None:
        return None
    parts: list[str] = [f'k = "{kind}"', f'n = {lua_str(node.name)}', "c = " + cls,
                        f"p = {{{r.x / cw:.5f}, {r.y / ch:.5f}}}",
                        f"s = {{{max(0.0, r.w / cw):.5f}, {max(0.0, r.h / ch):.5f}}}",
                        f"z = {z}"]
    if asset_key:
        parts.append(f'a = {lua_str(asset_key)}')
    if kind in SLICE_KINDS or kind in ("panel", "button"):
        rad = p.get("radius")
        if rad is not None:
            parts.append(f"r = {float(rad):.1f}")
    color = p.get("color") or p.get("top")
    if kind in ("divider", "scrim"):
        parts.append(f"bt = {float(p.get('alpha', 0.5)):.2f}")
        if color:
            parts.append(f"bg = {{{color[0]}, {color[1]}, {color[2]}}}")
    elif kind == "button":
        c = p.get("color") or (255, 255, 255)
        parts.append(f"tc = {{{c[0]}, {c[1]}, {c[2]}}}")
        parts.append(f"fs = {int(p.get('font_size', 26))}")
        parts.append(f"fa = \"{p.get('align', 'center')}\"")
        if p.get("variant"):
            parts.append(f'v = "{p["variant"]}"')
        if p.get("icon"):
            parts.append(f'icon = {lua_str("icon_" + p["icon"])}')
    elif kind == "text":
        parts.append(f"t = {lua_str(p.get('label', ''))}")
        parts.append(f"fs = {int(p.get('font_size', 24))}")
        parts.append(f"fa = \"{p.get('align', 'left')}\"")
        c = p.get("color")
        if c:
            parts.append(f"tc = {{{c[0]}, {c[1]}, {c[2]}}}")
        if p.get("label_en") and p.get("label_en") != p.get("label"):
            parts.append(f"te = {lua_str(p.get('label_en'))}")
    return "\t{" + ", ".join(parts) + "},"


def design_script(spec: DesignSpec) -> str:
    pal = spec.palette
    lines = []
    z = 0
    for node in spec.root.walk():
        if node.kind == "root":
            continue
        z += 1
        asset = spec.asset_for(node.name)
        entry = node_entry(node, spec, asset.key if asset else None, z)
        if entry:
            lines.append(entry)
    nodes_lua = "\n".join(lines)

    slices = ",\n\t".join(
        f'["{a.key}"] = {{{a.slice[0]:.0f}, {a.slice[1]:.0f}, {a.slice[2]:.0f}, {a.slice[3]:.0f}}}'
        for a in spec.assets if a.slice
    )

    header = f'''--!nonstrict
-- Design_{spec.slug}.lua  —  generated by Roblox UI Forge
-- Screen: {spec.title}   |   style: {pal.name}   |   canvas: {spec.canvas[0]}x{spec.canvas[1]}
--
-- HOW TO USE
-- 1. Upload the PNGs in assets/ to Roblox (Creator Dashboard -> Development Items -> Images)
-- 2. Paste the ids into ASSETS below (leave "" for anything you skip)
-- 3. Put UiForge.lua in ReplicatedStorage as a ModuleScript named "UiForge"
-- 4. Put this script in StarterPlayerScripts (or run it from Studio's command bar)

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UiForge = require(ReplicatedStorage:WaitForChild("UiForge"))

-- 1) paste your uploaded asset ids here -------------------------------------------------
local ASSETS = __ASSETS__

-- 2) 9-slice insets (source pixels) ----------------------------------------------------
local SLICES = {{
\t{slices}
}}

-- 3) the generated layout --------------------------------------------------------------
local NODES = {{
{nodes_lua}
}}

local function color3(v)
\treturn Color3.fromRGB(v[1], v[2], v[3])
end

local function buildScreen(parent)
\tUiForge.bindAssets(ASSETS)
\tlocal gui = UiForge.new("ScreenGui", {{
\t\tName = {lua_str(spec.slug.title())},
\t\tResetOnSpawn = false,
\t\tZIndexBehavior = Enum.ZIndexBehavior.Sibling,
\t\tIgnoreGuiInset = true,
\t}}, parent)

\tfor _, nd in ipairs(NODES) do
\t\tlocal position = UDim2.fromScale(nd.p[1], nd.p[2])
\t\tlocal size = UDim2.fromScale(nd.s[1], nd.s[2])
\t\tlocal inst

\t\tif nd.k == "text" then
\t\t\tinst = UiForge.new("TextLabel", {{
\t\t\t\tName = nd.n,
\t\t\t\tPosition = position,
\t\t\t\tSize = size,
\t\t\t\tBackgroundTransparency = 1,
\t\t\t\tText = nd.t or "",
\t\t\t\tFont = (nd.fs or 24) > 30 and Enum.Font.GothamBold or Enum.Font.Gotham,
\t\t\t\tTextSize = nd.fs or 24,
\t\t\t\tTextColor3 = nd.tc and color3(nd.tc) or Color3.fromRGB(255, 255, 255),
\t\t\t\tTextXAlignment = ({{ left = Enum.TextXAlignment.Left, center = Enum.TextXAlignment.Center, right = Enum.TextXAlignment.Right }})[nd.fa or "left"],
\t\t\t\tTextYAlignment = Enum.TextYAlignment.Center,
\t\t\t\tTextWrapped = true,
\t\t\t\tZIndex = nd.z,
\t\t\t}}, gui)

\t\telseif nd.k == "button" then
\t\t\tinst = UiForge.button(gui, {{
\t\t\t\tname = nd.n,
\t\t\t\tposition = position,
\t\t\t\tsize = size,
\t\t\t\tasset = nd.a,
\t\t\t\tradius = nd.r,
\t\t\t\ttext = nd.t or "",
\t\t\t\ttextSize = nd.fs or 26,
\t\t\t\ttextColor = nd.tc and color3(nd.tc) or Color3.fromRGB(255, 255, 255),
\t\t\t\tcolor = UiForge.Theme.accent,
\t\t\t\ticon = nd.icon,
\t\t\t\tzIndex = nd.z,
\t\t\t\tstates = {{ hover = (nd.a or "") .. "_hover", down = (nd.a or "") .. "_pressed" }},
\t\t\t}})

\t\telseif nd.k == "scrim" then
\t\t\tinst = UiForge.new("Frame", {{
\t\t\t\tName = nd.n,
\t\t\t\tPosition = position,
\t\t\t\tSize = size,
\t\t\t\tBackgroundColor3 = Color3.fromRGB(0, 0, 0),
\t\t\t\tBackgroundTransparency = 1 - (nd.bt or 0.5),
\t\t\t\tBorderSizePixel = 0,
\t\t\t\tZIndex = nd.z,
\t\t\t}}, gui)

\t\telseif nd.k == "divider" then
\t\t\tinst = UiForge.new("Frame", {{
\t\t\t\tName = nd.n,
\t\t\t\tPosition = position,
\t\t\t\tSize = size,
\t\t\t\tBackgroundColor3 = nd.bg and color3(nd.bg) or UiForge.Theme.stroke,
\t\t\t\tBackgroundTransparency = 0.25,
\t\t\t\tBorderSizePixel = 0,
\t\t\t\tZIndex = nd.z,
\t\t\t}}, gui)

\t\telse
\t\t\tinst = UiForge.new(nd.c, {{
\t\t\t\tName = nd.n,
\t\t\t\tPosition = position,
\t\t\t\tSize = size,
\t\t\t\tBackgroundTransparency = nd.a and 1 or 0,
\t\t\t\tBackgroundColor3 = nd.bg and color3(nd.bg) or UiForge.Theme.panel,
\t\t\t\tBorderSizePixel = 0,
\t\t\t\tImage = nd.a and (UiForge.asset(nd.a) or "") or "",
\t\t\t\tZIndex = nd.z,
\t\t\t}}, gui)
\t\t\tif nd.a then
\t\t\t\tUiForge.skin(inst, nd.a, UiForge.Theme.panel, nd.r)
\t\t\telseif nd.r then
\t\t\t\tUiForge.corner(inst, nd.r)
\t\t\tend
\t\tend
\tend
\treturn gui
end

return {{
\tbuild = buildScreen,
\tnodes = NODES,
\ttheme = UiForge.Theme,
}}
'''
    asset_table = ",\n\t".join(f'["{a.key}"] = ""' for a in spec.assets) or "-- no assets"
    out = header.replace("__ASSETS__", "{\n\t" + asset_table + "\n}")
    lib = LIBRARY.replace("__THEME__", theme_literal(pal)).replace(
        "__SLICES__", "{\n\t" + (slices or "") + "\n}")
    return out, lib


def bind_assets_script(spec: DesignSpec) -> str:
    lines = ["-- Bind_Assets.lua — generated by Roblox UI Forge",
             "-- Paste each uploaded rbxassetid next to its file name, then run:",
             "--   require(script.Parent.Bind_Assets).apply(gui)", "", "local M = {}", "",
             "M.map = {"]
    for a in spec.assets:
        lines.append(f'\t["{a.key}"] = "",  -- assets/{a.category}/{a.filename}')
    lines += ["}", "", "function M.apply(gui)",
              "\tlocal ReplicatedStorage = game:GetService(\"ReplicatedStorage\")",
              "\tlocal UiForge = require(ReplicatedStorage:WaitForChild(\"UiForge\"))",
              "\tUiForge.bindAssets(M.map)",
              "\tfor _, inst in ipairs(gui:GetDescendants()) do",
              "\t\tlocal id = M.map[inst.Name]",
              "\t\tif id and id ~= \"\" and inst:IsA(\"ImageLabel\") or inst:IsA(\"TextButton\") then",
              "\t\t\tif id and id ~= \"\" then inst.Image = id end",
              "\t\tend",
              "\tend",
              "\treturn gui", "end", "", "return M", ""]
    return "\n".join(lines)


def quick_build_script(spec: DesignSpec) -> str:
    """Self-contained builder: paste into Studio's command bar, no uploads needed."""
    pal = spec.palette
    body = []
    z = 0
    for node in spec.root.walk():
        if node.kind == "root":
            continue
        z += 1
        r, p = node.rect, node.props
        cw, ch = spec.canvas
        pos = f"UDim2.fromScale({r.x / cw:.5f}, {r.y / ch:.5f})"
        size = f"UDim2.fromScale({max(0.0, r.w / cw):.5f}, {max(0.0, r.h / ch):.5f})"
        name = lua_str(node.name)
        if node.kind == "text":
            c = p.get("color") or (255, 255, 255)
            align = {"left": "Left", "right": "Right", "center": "Center"}.get(p.get("align", "left"), "Left")
            body.append(
                f"mk(\"TextLabel\", {name}, {pos}, {size}, {{ BackgroundTransparency = 1, Text = {lua_str(p.get('label', ''))}, "
                f"Font = Enum.Font.{'GothamBold' if int(p.get('font_size', 24)) > 30 else 'Gotham'}, "
                f"TextSize = {int(p.get('font_size', 24))}, TextColor3 = Color3.fromRGB{tuple(c)}, "
                f"TextXAlignment = Enum.TextXAlignment.{align}, TextWrapped = true, ZIndex = {z} }})")
        elif node.kind == "scrim":
            body.append(f"mk(\"Frame\", {name}, {pos}, {size}, {{ BackgroundColor3 = Color3.new(0,0,0), "
                        f"BackgroundTransparency = {1 - float(p.get('alpha', 0.5)):.2f}, ZIndex = {z} }})")
        else:
            c = p.get("top") or p.get("color") or pal.panel
            if node.kind == "button":
                variant = p.get("variant", "primary")
                c = {"primary": pal.accent, "secondary": pal.panel_hi, "ghost": pal.panel,
                     "danger": pal.danger, "success": pal.success}.get(variant, pal.panel)
                body.append(
                    f"mk(\"TextButton\", {name}, {pos}, {size}, {{ BackgroundColor3 = Color3.fromRGB{tuple(c)}, "
                    f"Text = {lua_str(p.get('label', ''))}, Font = Enum.Font.GothamBold, TextSize = {int(p.get('font_size', 26))}, "
                    f"TextColor3 = Color3.fromRGB{tuple(p.get('color') or (255, 255, 255))}, AutoButtonColor = true, ZIndex = {z} }})")
            elif node.kind == "divider":
                c = p.get("color") or pal.stroke
                body.append(f"mk(\"Frame\", {name}, {pos}, {size}, {{ BackgroundColor3 = Color3.fromRGB{tuple(c)}, "
                            f"BackgroundTransparency = 0.25, ZIndex = {z} }})")
            else:
                cls = "ImageLabel" if node.kind in IMAGE_KINDS else "Frame"
                extra = "Image = \"\", " if cls == "ImageLabel" else ""
                body.append(f"mk(\"{cls}\", {name}, {pos}, {size}, {{ {extra}"
                            f"BackgroundColor3 = Color3.fromRGB{tuple(c)}, ZIndex = {z} }})")
            rad = p.get("radius")
            if rad is not None:
                body.append(f"corner(last, {float(rad):.0f})")
    return f'''-- Studio_QuickBuild.lua — generated by Roblox UI Forge
-- Zero-upload preview: paste this whole file into Studio's command bar
-- (View > Command Bar) and press Enter.  It builds "{spec.title}" with solid
-- colours + corners so you can judge the layout before uploading any image.

local gui = Instance.new("ScreenGui")
gui.Name = "{spec.slug}"
gui.ResetOnSpawn = false
gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
gui.IgnoreGuiInset = true

local last
local function mk(class, name, position, size, props)
\tlocal inst = Instance.new(class)
\tinst.Name = name
\tinst.Position = position
\tinst.Size = size
\tinst.BorderSizePixel = 0
\tfor k, v in pairs(props or {{}}) do inst[k] = v end
\tinst.Parent = gui
\tlast = inst
\treturn inst
end

local function corner(inst, radius)
\tif not inst then return end
\tlocal c = Instance.new("UICorner")
\tc.CornerRadius = UDim.new(0, radius)
\tc.Parent = inst
end

{chr(10).join(body)}

gui.Parent = game:GetService("CoreGui")
print("[Roblox UI Forge] built {spec.title} into CoreGui")
'''


def auto_scale_script() -> str:
    return '''-- AutoScale.lua — keeps the UI readable on phones and 4K screens.
-- Put it in StarterPlayerScripts; it scales the whole ScreenGui to the viewport.

local Players = game:GetService("Players")
local player = Players.LocalPlayer

local TARGET_HEIGHT = 1080

local function apply(gui)
	local scale = Instance.new("UIScale")
	scale.Name = "ForgeAutoScale"
	scale.Scale = math.clamp(workspace.CurrentCamera.ViewportSize.Y / TARGET_HEIGHT, 0.55, 1.6)
	scale.Parent = gui
	workspace.CurrentCamera:GetPropertyChangedSignal("ViewportSize"):Connect(function()
		scale.Scale = math.clamp(workspace.CurrentCamera.ViewportSize.Y / TARGET_HEIGHT, 0.55, 1.6)
	end)
end

for _, gui in ipairs(player:WaitForChild("PlayerGui"):GetChildren()) do
	if gui:IsA("ScreenGui") then apply(gui) end
end
player.PlayerGui.ChildAdded:Connect(function(child)
	if child:IsA("ScreenGui") then task.wait(0.1) apply(child) end
end)
'''
